# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0003_document_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='title',
        ),
    ]
